# Generated by Django 4.2.1 on 2023-05-19 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0002_role_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
