# Generated by Django 4.2.1 on 2023-05-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0003_remove_userprofile_role_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model', models.CharField(max_length=255)),
                ('DMS_Stock', models.IntegerField(db_column='DMS Stock', max_length=255)),
                ('WS_TGT', models.IntegerField(db_column='WS TGT')),
                ('WS_ACH', models.IntegerField(db_column='WS ACH')),
                ('BAL_WS', models.IntegerField(db_column='BAL WS')),
                ('Total_Probable_stock', models.IntegerField(db_column='Total Probable Stock')),
            ],
        ),
    ]
