# Generated by Django 4.2.1 on 2023-05-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0004_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='DMS_Stock',
            field=models.IntegerField(db_column='DMS Stock'),
        ),
    ]
