# Generated by Django 4.2.1 on 2023-05-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0005_alter_sample_dms_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='Total_Probable_stock',
            new_name='Total_Probable_Stock',
        ),
    ]
