# Generated by Django 4.2.1 on 2023-05-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0006_rename_total_probable_stock_sample_total_probable_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='team_leader_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_leader_name', models.CharField(max_length=255)),
            ],
        ),
    ]
