# Generated by Django 4.2.1 on 2023-05-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0007_team_leader_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLeaderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_leader_data', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('team_data_territory', models.CharField(max_length=100)),
                ('per_day_asking', models.FloatField()),
                ('test_drive_percentage', models.CharField(max_length=10)),
                ('home_visit_percentage', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='team_leader_data',
        ),
    ]
