# Generated by Django 4.2.1 on 2023-05-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0008_teamleaderdata_delete_team_leader_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamleaderdata',
            old_name='team_data_territory',
            new_name='team_leader_name',
        ),
        migrations.RenameField(
            model_name='teamleaderdata',
            old_name='team_leader_data',
            new_name='team_leader_territory',
        ),
        migrations.RemoveField(
            model_name='teamleaderdata',
            name='date_of_joining',
        ),
        migrations.AddField(
            model_name='teamleaderdata',
            name='enquiry_total',
            field=models.IntegerField(null=True),
        ),
    ]
