# Generated by Django 4.2.1 on 2023-06-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0009_rename_team_data_territory_teamleaderdata_team_leader_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='salesEx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mspin', models.IntegerField()),
                ('dse_name', models.CharField(max_length=100)),
                ('ageing', models.CharField(max_length=100)),
                ('team_leader_name', models.CharField(max_length=100)),
                ('unit_name', models.CharField(max_length=100)),
                ('enquiry_total', models.IntegerField()),
                ('home_visit', models.ImageField(upload_to='')),
                ('test_drive', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='teamleaderdata',
            name='home_visit_percentage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teamleaderdata',
            name='test_drive_percentage',
            field=models.IntegerField(),
        ),
    ]
