# Generated by Django 4.2.1 on 2023-06-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0010_salesex_alter_teamleaderdata_home_visit_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesex',
            name='enquiry_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salesex',
            name='home_visit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salesex',
            name='test_drive',
            field=models.IntegerField(),
        ),
    ]
